### PR TITLE
Sockets configuration

### PR DESCRIPTION
**Pull request by DanMMX**
I created a sockets configuration on the generator, give me a change to test it until next week, I don't think I'll be changing anything else (already tested thoroughly) however something might come up on a real app 😸 

I created the PR so you can start checking on it and let me know if you have any comments

Let me know what you think @diegohaz

### CODE REVIEW

**Comment by diegohaz** [comment]
It looks pretty good, Dan. Thank you very much.

I'll take a closer look at this (trying the generator) over the course of the week. Tell me when you're done.

The CI is intermittent. Don't know how to fix it yet.

**Comment by DanMMX** [comment]
Yeah that's what I meant too, I'll be using it in the course of the week.

About the CI, not sure it's the CI itself, random tests fail on my local too, might be some mongoose dependency that has probably changed.

**Comment by DanMMX** [comment]
So @diegohaz I've been using this a couple of weeks and works nice 😄 
let me know if you think something should be changed

**Comment by Angelk90** [comment]
@DanMMX , @diegohaz : Are there any news?

**Comment by DanMMX** [comment]
@Angelk90 you can check out #243 or use my repo @ https://github.com/DanMMX/rest/tree/sockets

**Comment by DanMMX** [comment]
closed this PR due to #243

**Comment by Angelk90** [comment]
@DanMMX : Can I ask you something, but that doesn't have to do with sockets?

**Pull request closed without merging**
